
first = ["Selenium WebDriver + Java для начинающих (платный) - https://www.udemy.com/selenium-webdriver-and-java-for-beginners/",
"Software Testing - Udacity (бесплатный) - https://classroom.udacity.com/courses/cs258",
"QA Start - ITDVN (платный) - https://itvdn.com/ru/specialities/qa#",
"Каталог курсов (программирование, администрирование, БД) - https://stepik.org/catalog",
"Каталог курсов (тестирование, программирование, администрирование, БД) - https://geekbrains.ru/",
"Codecademy - https://www.codecademy.com/apis",
"Упражнения по SQL - http://www.sql-ex.ru/",
"Курс по SQL (Eng) - https://sqlbolt.com/",
"Курсы кодинг - http://exercism.io/",
"Курсы кодинг - http://codecademy.com",
"Курсы кодинг - https://checkio.org/",
"Курсы кодинг - https://coursehunters.net/source/udemy",
"Курсы кодинг - https://www.codeschool.com",
"Интерактивный учебник по SQL (бесплатный) - http://www.sql-tutorial.ru/",
"Datamonkey (платный) - http://datamonkey.pro/",
"Тесты на знание сферы тестирования и QA - http://www.quizful.net/test/quality-assurance-basics",
" - http://www.quizful.net/test/software_testing_basics",
"Каталог курсов - http://www.luxoft-training.ru/training/katalog_kursov/",
"Английский за 16 часов с Дмитрием Петровым - https://tvkultura.ru/brand/show/brand_id/14505/",
"Задачи для тестирования - http://testingchallenges.thetestingmap.org",
"Бесплатные практические уроки по программированию - https://ru.code-basics.com/",
"Обучение git - https://learngitbranching.js.org/"
]

linki = ["Сайт с очень большим количеством платных курсов и бесплатных материалов - http://software-testing.ru/",
         "Материалы для сдачи экзамена на сертификат ISTQB - https://www.rstqb.org/ru/istqb-downloads.html",
         "Библия QA - https://github.com/VladislavEremeev/QA_bible",
         "Список книг по всем видам тестирования, управлению проектами, тест-менеджменту и многое другое - http://okiseleva.blogspot.ru/2014/02/blog-post_6.html",
         "Библия QA - https://github.com/VladislavEremeev/QA_bible",
         "Небольшой ликбез по нагрузочному (методология) - https://xwizard-test.blogspot.ru/2015/01/blog-post_30.html",
         "Список книг по всем видам тестирования, управлению проектами, тест-менеджменту и многое другое - http://okiseleva.blogspot.ru/2014/02/blog-post_6.html",
         "Плагины для Firefox - https://www.youtube.com/watch?v=ZRorJHShXzs&feature=youtu.be",
         "вопросы про тестирование с собеседований - https://habrahabr.ru/post/257529/",
         "Расширения для Chrome - http://software-testing.ru/library/testing/general-testing/2242-useful-google-chrome-extensions-testing-software",
         "Полный чек-лист тестирования веб-приложения - http://software-testing.ru/library/testing/testing-for-beginners/2478-complete-web-application-testing-checklist",
         "Практика SoapUI/Rest API - http://okiseleva.blogspot.ru/2017/04/users-soap-rest.html",
         "Основы Agile (Борис Вольфсон, AgileDays-2015) - https://vimeo.com/123181716",
         "Charles: незаменимый тул в арсенале QA-инженера - https://habrahabr.ru/company/redmadrobot/blog/269109/",
         "Статьи по тестированию от Лаборатории Качества - http://quality-lab.ru/blog/",
         "Материалы ISTQB - http://www.rstqb.org/ru/istqb-downloads.html",
         "Видеолекции Техносферы по QA web-приложений - https://habrahabr.ru/company/mailru/blog/260105/",
         "ISTQB Сертификация. Опыт сдачи - http://julik.space/2016/08/31/istqb-certification-my-experience/",
         "Мой опыт сдачи ISTQB сертификации - https://dou.ua/lenta/articles/ISTQB-reflections/",
         "7 лучших ферм устройств для тестирования мобильных приложений - https://habrahabr.ru/company/microsoft/blog/333606/",
         "Туториалы и читлисты (Eng) - https://www.guru99.com/software-testing.html",
         "Туториалы на (Eng) - http://www.softwaretestinghelp.com/",
         "Туториалы на (Eng) - istqbexamcertification.com",
         "Туториалы на (Eng) - https://www.tutorialspoint.com/software_testing_dictionary/",
         "Канал в телеграм - https://t.me/qasoft",
         "Русскоязычное сообщество тестировщиков (Slack, разные каналы) - https://software-testers.herokuapp.com/",
         "Коллекция видео с конференций QA - https://devtube.ru/hubs/14",
         "Подборка материалов для подготовки к QA Interview - https://xwizard-test.blogspot.ru/2017/02/qa-interview-qa-automation-python-linux.html",
         "Азы тестирования подробно и доходчиво - http://testbase.ru/",
         "Видеолекция М.Поляруша о локаторах - https://www.youtube.com/watch?v=ahhaMbjqrxM&t=2157s",
         "Краткая шпаргалка по всем командам Git - http://rogerdudler.github.io/git-guide/index.ru.html",
         "Материалы для самоподготовки - https://training.by/News/Details/94/%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B_%D0%B4%D0%BB%D1%8F_%D1%81%D0%B0%D0%BC%D0%BE%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B8_%D0%B4%D0%BB%D1%8F_%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D1%89%D0%B8%D0%BA%D0%BE%D0%B2_%D0%B8_%D0%BD%D0%B5_%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE",
         "Selenium для Python (Почти полное руководство) - https://habrahabr.ru/post/248559/",
         "Как протестировать поле логина и пароля. - https://testitquickly.com/2009/09/09/vvodeste-loginu-la-adnaklassni6i/",
         "Пример тест плана - https://ru.scribd.com/document/39391857/TestPlanTemplateV1-0",
         "Чек-лист для проверки мобильных приложений - https://www.guru99.com/testing-mobile-apps.html",
         "Чек-лист для проверки мобильных приложений - http://www.softwaretestinghelp.com/beginners-guide-to-mobile-application-testing/",
         "40 Самых популярных вопросов на собеседовании для моб. тестировщика - http://www.softwaretestinghelp.com/mobile-testing-interview-questions-answers/",
         "Top 100+ вопросов по Selenium для собеседования, с ответами. - https://geteasyqa.com/ru/qa/best-selenium-interview-questions/",
         "Универсальная схема для тестирования веб-приложений - https://dou.ua/lenta/articles/scheme-for-qa/?utm_content=id&utm_source=telegram&utm_campaign=smm_posts&utm_term=&utm_medium=kuku",
         "Тесты для функционального тестирования Windows приложений - http://download.microsoft.com/download/8/D/9/8D995CB3-2C3E-43B4-97D3-B372FBF6C7EF/STARTS%20Quality%20Bar%20FY2016.pdf",
         "Основы компьютерных сетей - https://habr.com/post/307252/",
         "Сети для самых маленьких - https://habr.com/post/134892/",
         "UI controls на русском. Список терминов для фронта - https://habr.com/ru/post/223929/",
         "Собрание чеклистов для проверок - https://checkvist.com/checklists/476089-checklists-base",
         "Гайд по devtools - https://developers.google.com/web/tools/chrome-devtools",
         "Тестирование удобства использования и доступности - https://www.cjcid.com/articles/unexpected-a11y-tips/",
         "Вопросы на собеседовании - https://github.com/Vladislav610/QA_bible/blob/master/README.md"
         ]

chats = ["Обсуждение курсов, отзывы о них - https://t.me/qa_courses",
         "Тренировочные собеседования, интересные обсуждения - https://t.me/qa_interviews",
         "чат, ориентированный на джуниоров - https://t.me/qajuniors",
         "Канал книг по тестированию - https://t.me/booksqa",
         "Всё про Selenium/Selenium WebDriver - https://selenium2.ru/",
         "Мануал по xPath - https://docs.google.com/document/d/1PdfKMDfoqFIlF4tN1jKrOf1iZ1rqESy2xVMIj3uuV3g/pub",
         "Читлист для веб (уязвимости) - https://defcon.ru/web-security/4349/",
         "Требования к джунам (Хабр)= - https://habrahabr.ru/company/rambler-co/blog/303254/",
         "Блог Андрея Мясникова - http://lazy-tester.blogspot.com.by/",
         "Блог Ольги Назиной (Киселева) - http://okiseleva.blogspot.ru/",
         "Блог Алексея Лупан - https://testitquickly.com/",
         "Блог Натальи Руколь - http://natalyarukol.ru/",
         "Блог Святослава Куликова - http://svyatoslav.biz/",
         "Радио QA - Подкаст тестировщиков - http://radio-qa.com/",
         "SoftwareQATest (англ. яз.) - http://www.softwareqatest.com/",
         "Blackbox instructions. © Cem Kaner (Eng) - http://www.testingeducation.org/BBST/",
         "С чего начинать © Shoo - https://toster.ru/answer?answer_id=361683",
         "Что знать джуну © Shoo - https://toster.ru/q/148847?answer_id=418807",
         "Сообщество автоматизаторов - http://automated-testing.info/",
         "Локаторы в селениум © Сергей Пирогов - http://automation-remarks.com/2017/locators/index.html",
         "Блоги на (Eng) - https://www.qasymphony.com/blog/",
         "Блоги на (Eng) - https://www.keycdn.com/blog/page/2/",
         "Фермы для тестирования мобилок - https://habrahabr.ru/company/microsoft/blog/333606/",
         "Чит-лист по Web UI контролам от Игоря Любина - http://wiki.software-testing.ru/%D0%A7%D0%B8%D1%82-%D0%BB%D0%B8%D1%81%D1%82_%D0%BF%D0%BE_Web_UI_%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%B0%D0%BC_%D0%BE%D1%82_%D0%98%D0%B3%D0%BE%D1%80%D1%8F_%D0%9B%D1%8E%D0%B1%D0%B8%D0%BD%D0%B0",
         "Чит-лист регистрации от Алексея Лупана - http://wiki.software-testing.ru/%D0%A7%D0%B8%D1%82-%D0%BB%D0%B8%D1%81%D1%82_%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8_%D0%BE%D1%82_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D1%8F_%D0%9B%D1%83%D0%BF%D0%B0%D0%BD%D0%B0",
         "Знакомство с структурой клиент серверных приложений - https://itvdn.com/ru/video/web_testing?utm_source=yb_full_webtest",
         "В погоне за производительностью: психология пользователя- Денис Мишунов - https://www.youtube.com/watch?v=i9cOoipvST8",
         "Сборник материалов по использованию Nightwatch.js - https://trello.com/b/2hvbzg9y/nightwatchjs",
         "Тестирование API © Антон Серпутько, Terrasoft, StartIT - https://youtube.com/watch?v=XR0YXH0ue2I",
         "Как приручить Charles Proxy - https://habr.com/ru/company/youla/blog/527648/"
         ]

books = ["Интерактивный учебник по SQL (бесплатный) - http://www.sql-tutorial.ru/",
         "Программирование по-простому - https://metanit.com/",
         "Подборка книг - http://okiseleva.blogspot.com/2014/02/blog-post_6.html?m=1",
        "Интерактивный учебник по SQL (бесплатный) - http://www.sql-tutorial.ru/",
        "Datamonkey (платный) - http://datamonkey.pro/",
        "Программирование по-простому - https://metanit.com/",
        "«The History of Software Testing» - http://www.testingreferences.com/testinghistory.php",
        "«The Growth of Software Testing» David Gelperin, Bill Hetzel - https://www.researchgate.net/publication/234808293_The_growth_of_software_testing",
        "Очумелая английская грамматика - https://iloveenglish.ru/stories/view/ochymelaya_anglijskaya_grammatika",
        "Подборка книг по тестированию - https://www.livelib.ru/selection/686598-bibliotechka-qa-spetsialista",
        "Книга по тестированию геймдева - https://computernote.files.wordpress.com/2011/04/course-technology-game-testing-all-in-one-feb20051.pdf",
        "Компьютерные сети. Принципы, технологии, протоколы - https://www.labirint.ru/books/511422/",
        "Компьютерные сети.Олифер - https://www.labirint.ru/books/310025/",
        "Rosetta Stone and Cookbook - http://scraping.pro/res/xpath-cheat/xpath_css_dom_ref.pdf",
        "The Art of Test Automation - Selenide + Jav - https://drive.google.com/file/d/1qRHCZGZ88JFxn0oALzA0VyfZmxvMvQbX/view",
        "Technical Skills for Agile Testers - https://drive.google.com/file/d/15YhMRqwM_sOBIz0PRBEAzbWGXVbXsq0E/view",
        "Gurock (TestRail) - Performance-testing - https://drive.google.com/drive/folders/1nxhaL97HlcQ7w17jQKOoD_G1L-puNTVc",
        "Канал книг по тестированию - https://t.me/booksqa"
]

engl = ["100 самых первых слов для составления баг-репортов и тест-кейсов на английском языке - https://training.qatestlab.com/blog/helpful-materials/100-must-have-words-in-english-for-the-qa-engineer/",
"Английский по плейлистам - https://www.youtube.com/channel/UC_3oKG5Szq-m6Xz-MjRZgpw",
"Learn English with EnglishClass101.com - https://www.youtube.com/channel/UCeTVoczn9NOZA9blls3YgUg",
"English with Lucy - https://www.youtube.com/channel/UCz4tgANd4yy8Oe0iXCdSWfA",
"Полиглот. Выучим английский за 16 часов! - https://youtube.com/playlist?list=PL66DIGaegedqtRaxfVsk6vH5dBDuL5w92",
"Lingualeo - https://lingualeo.com/",
"Language Practice Community - https://www.free4talk.com",
"Busuu - https://www.busuu.com/",
"Duolingo - https://www.duolingo.com/",
"OK English - уроки английского языка - https://www.youtube.com/c/Ok-englishRu",
"Английский с нуля - https://lingust.ru/english",
"Madbook - https://madbook.org/books",
"Увлекательный английский - https://fenglish.ru/",
"Memrise - https://www.memrise.com/ru/",
"Reverso Context - https://chrome.google.com/webstore/detail/reverso-%E2%80%93-translation-dic/onhiacboedfinnofagfgoaanfedhmfab?hl=ru",
"Grammarly - https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=ru&ref=hrstack"

]

pyth = ["Первые шаги в Питоне. Онлайн учебник (бесплатный) - https://pythontutor.ru/",
"официальная документация как писать автотесты Python+Selenium - https://selenium-python.readthedocs.io/index.html",
"Pytest - фреймворк для написания тестов на Python (мощная параметризация, фикстуры и другие плюшки) - https://docs.pytest.org/en/latest/",
"основы основ, хорошо для тех кто никогда не программировал - https://stepik.org/course/67/",
"чуть посложнее, зато все что нужно тестировщику - ооп, апи, xml - https://stepik.org/course/512",
"Азы синтаксиса и понятий. На сайте английская версия, в приложении - русская - https://www.sololearn.com/Course/Python/",
"курс по питону от мэйлру & МФТИ на русском, лучше брать не с нуля, а после степика - https://www.coursera.org/specializations/programming-in-python",
"учебник по Джанго на русском - https://djbook.ru/rel1.9/",
"курс по питону вводный с абсолютного нуля (ENG) - https://www.coursera.org/specializations/python",
"пример авто-теста pytest+requests - https://github.com/SunInJuly/api_example",
"практика по регулярным выражениям - https://www.hackerrank.com/domains/regex",
"Автоматизация тестирования с помощью Selenium и Python (курс Юлии Лях) - https://stepik.org/course/575/",
"Классный roadmap по изучению Python - https://github.com/GnuriaN/Python-Roadmap"


]